version: '3.7'

services:
  proxy:
    image: nginx:latest
    container_name: proxy
    ports:
      - '80:80'
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    restart: 'unless-stopped'

  backend-server:
    container_name: deploy-app
    image: 'deploy-app'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/deploy-app/src
      - ./node_modules
    ports:
      - 3000:3000
    restart: 'unless-stopped'
